# Generated by Django 3.2.4 on 2021-07-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0012_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
