# Generated by Django 3.2.5 on 2021-08-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0016_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.FileField(default='avatar.jpg', upload_to='Identity'),
        ),
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
