# Generated by Django 3.2.5 on 2021-08-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0017_auto_20210805_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
