# Generated by Django 3.2.5 on 2021-08-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210811_0843'),
        ('customuser', '0019_auto_20210811_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.skills'),
        ),
    ]
