# Generated by Django 3.2.5 on 2021-08-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0020_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
