# Generated by Django 3.2.5 on 2021-08-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210811_0908'),
        ('customuser', '0021_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='category.Skills'),
        ),
    ]
