# Generated by Django 3.2.5 on 2021-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0024_auto_20210821_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skills_1',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills_3',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(max_length=100, null=True),
        ),
    ]
