# Generated by Django 3.2.4 on 2021-07-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_events_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_1', models.TextField(max_length=2000, null=True)),
                ('ques_2', models.TextField(max_length=2000, null=True)),
                ('ques_3', models.TextField(max_length=2000, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
