# Generated by Django 3.2.5 on 2021-08-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='file_1',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
