# Generated by Django 3.2.5 on 2021-08-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_requestform_file_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestform',
            options={'verbose_name_plural': 'Request Form'},
        ),
    ]
