# Generated by Django 3.2.4 on 2021-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Request as Volunteer'), (2, 'Interested'), (3, '')]),
        ),
    ]
