# Generated by Django 3.2.5 on 2021-08-11 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_country_district_municipality_province_skills_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.province'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.district'),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.country'),
        ),
        migrations.AddField(
            model_name='ward',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.municipality'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
