# Generated by Django 3.2.5 on 2021-08-11 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210811_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='Municipality',
            new_name='municipality',
        ),
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='district',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='municipality',
        ),
    ]
