# Generated by Django 3.2.5 on 2021-08-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0023_auto_20210813_2029'),
        ('category', '0004_auto_20210811_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event categories'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
    ]
