# Generated by Django 3.2.4 on 2021-06-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
