# Generated by Django 3.2.4 on 2021-07-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_user_images'),
        ('customuser', '0006_user_username'),
    ]

    operations = [
    ]
