# Generated by Django 3.2.4 on 2021-06-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='banner',
        ),
    ]
