# Generated by Django 3.2.4 on 2021-07-13 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_events_banner'),
        ('volunteer', '0002_auto_20210707_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevents',
            name='user_details',
            field=models.FileField(default='avatar.jpg', upload_to='request_volunteer'),
        ),
        migrations.CreateModel(
            name='interestedevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
