# Generated by Django 3.2.4 on 2021-07-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20210707_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevents',
            name='user_details',
            field=models.FileField(default='avatar.jpg', upload_to='request_volunteer'),
        ),
    ]
