# Generated by Django 3.2.4 on 2021-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_remove_requestevents_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevents',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
