# Generated by Django 3.2.4 on 2021-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_alter_requestevents_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestevents',
            old_name='description',
            new_name='ans_1',
        ),
        migrations.AddField(
            model_name='requestevents',
            name='ans_2',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='requestevents',
            name='ans_3',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='requestevents',
            name='ques_1',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='requestevents',
            name='ques_2',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='requestevents',
            name='ques_3',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
