# Generated by Django 3.2.4 on 2021-07-26 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210717_1855'),
        ('volunteer', '0007_auto_20210726_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
