# Generated by Django 3.2.5 on 2021-08-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_alter_requestevents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevents',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
