# Generated by Django 3.2.5 on 2021-08-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_requestevents_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevents',
            name='file_1',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
