# Generated by Django 3.2.5 on 2021-08-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0011_requestevents_file_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestedevents',
            options={'verbose_name_plural': 'Interested Event'},
        ),
        migrations.AlterModelOptions(
            name='requestevents',
            options={'verbose_name_plural': 'Request Event'},
        ),
    ]
