# Generated by Django 3.2.5 on 2022-02-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0012_auto_20210813_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevents',
            name='task_assigned',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
