# Generated by Django 3.2.5 on 2022-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0013_requestevents_task_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestevents',
            name='task_assigned',
            field=models.TextField(default='False', max_length=2000, null=True),
        ),
    ]
